# Numpy

`NumPy` es una librería para hacer computos numéricos en Python. Es la base de muchas otras librerías científicas. Entre otras cosas, nos permite:

- Utilizar arreglos multidimensionales.
- Utilizar funciones matemáticas.
- Utilizar herramientas de álgebra lineal.

Necesitamos conocer esta librería (en concreto, el manejo de arreglos) para poder entender el funcionamiento de `pandas`. Para comenzar a trabajar vamos a importar la librería y crear un pequeño arreglo de elementos aleatorios.

In [50]:
import numpy as np

data = np.random.randn(2,4) #distribucion normal, mean = 0 , var=1
data

array([[-0.36652484, -0.27432782,  0.819003  ,  1.33545952],
       [ 0.65191197,  0.00687344,  0.30127806, -0.18836907]])

A diferencia de una lista, podemos hacer operaciones matriciales, como multiplicar el arreglo `data` por un escalar:

In [2]:
data*10

array([[  0.95543632,  30.36470997, -10.50833308,   1.49222148],
       [-14.23464378,  -0.65575127,   9.21746153,  -1.18240001]])

o sumarle una matriz:

In [3]:
data + data

array([[ 0.19108726,  6.07294199, -2.10166662,  0.2984443 ],
       [-2.84692876, -0.13115025,  1.84349231, -0.23648   ]])

### Crear arreglos

Podemos crear arreglos a partir de una lista:

In [8]:
data1 = [1, 1, 2, 3, 5]
print(type(data1))
arr1 = np.array(data1)
arr1


<class 'list'>


array([1, 1, 2, 3, 5])

In [9]:
data2 = [[1, 1, 2, 3], [5, 8, 13, 21]]
arr2 = np.array(data2)
arr2

array([[ 1,  1,  2,  3],
       [ 5,  8, 13, 21]])

Para preguntar el número de dimensiones utilizamos `ndim`. Para preguntar las dimensiones utilizamos `shape`.

In [20]:
arr2.ndim

2

In [11]:
#shape entrega la forma del arreglo
arr2.shape

(2, 4)

### Accediendo a elementos

Para obtener un elemento:

In [12]:
arr1

array([1, 1, 2, 3, 5])

In [13]:
arr1[4]

5

In [14]:
arr2

array([[ 1,  1,  2,  3],
       [ 5,  8, 13, 21]])

In [15]:
#Acceder a un elemento
arr2[1][2]

13

In [16]:
# Podemos acceder de esta forma también.
arr2[1, 2]

13

Los arreglos son mutables:

In [17]:
arr1[3] = 300
arr1

array([  1,   1,   2, 300,   5])

In [21]:
arr2[1, 2] = 100
arr2

array([[  1,   1,   2,   3],
       [  5,   8, 100,  21]])

### arange

También tenemos un equivalente a `range` llamado `arange`, pero que genera un arreglo.

In [25]:
np.arange(2, 11)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

### Operaciones sobre arreglos

Algunas operaciones que se pueden hacer sobre un arreglo son:

In [32]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr
arr2= np.array([[2, 2, 2, 2], [2, 2, 2, 2]])
arr2

array([[2, 2, 2, 2],
       [2, 2, 2, 2]])

In [33]:
arr * arr2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [34]:
arr + 1

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [35]:
(arr + 1) - arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [36]:
1 / arr

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.2       , 0.16666667, 0.14285714, 0.125     ]])

In [ ]:
arr ** 0.5

### _Slices_

Podemos extraer partes de un arreglo tal como en las listas. También podemos usar esto para cambiar los valores de dichos elementos.

In [37]:
arr = np.arange(3,15)
arr

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [38]:
arr[3:6]

array([6, 7, 8])

In [39]:
arr[3:6] = 1
arr

array([ 3,  4,  5,  1,  1,  1,  9, 10, 11, 12, 13, 14])

### Indexando con booleanos

Podemos utilizar comparaciones booleanas con los arreglos:

In [40]:
arr = np.array([0, 0, 1, 1, 2, 2])
arr == 1

array([False, False,  True,  True, False, False])

Y usarlo para acceder a valores en otros arreglos. Vamos a crear un arreglo multidimensional e ingresar el arreglo anterior como índice:

In [44]:
arr2 = np.random.randn(6, 3)
arr2

array([[ 0.11640232, -2.80335611, -0.30932357],
       [ 0.52281413, -0.10264561, -0.33417724],
       [-0.32476409, -0.46577471, -1.70484425],
       [ 0.55824429,  1.73233722,  0.07833994],
       [-1.17802706, -0.25466503,  0.94570898],
       [ 0.2316407 , -2.45346674,  0.74105607]])

In [45]:
arr2[arr == 1]

array([[-0.32476409, -0.46577471, -1.70484425],
       [ 0.55824429,  1.73233722,  0.07833994]])

Y también podemos negar la condición:

In [46]:
arr2[~(arr == 1)]

array([[ 0.11640232, -2.80335611, -0.30932357],
       [ 0.52281413, -0.10264561, -0.33417724],
       [-1.17802706, -0.25466503,  0.94570898],
       [ 0.2316407 , -2.45346674,  0.74105607]])

### Transponer un arreglo

Es posible obtener la transpuesta de un arreglo rápidamente.

In [52]:
arr = np.random.randn(6, 3)
arr

array([[ 0.6099659 , -1.17234997, -2.11919551],
       [-0.32166243, -0.31702654,  0.34270888],
       [ 0.6179648 , -0.86509918,  0.96069649],
       [ 2.19065425,  0.07901555,  1.26175465],
       [-0.23685505,  0.163141  , -0.53923112],
       [ 1.83265663, -0.94620587,  0.73285684]])

In [53]:
arr.T

array([[ 0.6099659 , -0.32166243,  0.6179648 ,  2.19065425, -0.23685505,
         1.83265663],
       [-1.17234997, -0.31702654, -0.86509918,  0.07901555,  0.163141  ,
        -0.94620587],
       [-2.11919551,  0.34270888,  0.96069649,  1.26175465, -0.53923112,
         0.73285684]])

### Otras funciones

Tenemos acceso a algunas funciones de estadística básicas. Por ejemplo `sum`, `mean` y `std` nos permiten respectivamente sacar la suma, el promedio y la desviación estándar de un arreglo.

In [56]:
arr = np.random.randn(10)
arr

array([ 0.75975482, -1.22878754,  1.55216138,  1.13019796, -1.15386311,
       -0.77331637, -1.05900859,  0.07576187, -0.25873269,  0.11760762])

In [57]:
arr.sum()

-0.8382246478208802

In [58]:
arr.mean()

-0.08382246478208802

In [59]:
arr.std()

0.940258903160401

También podemos ordenar:

In [68]:
arr.sort()
arr

array([-1.22878754, -1.15386311, -1.05900859, -0.77331637, -0.25873269,
        0.07576187,  0.11760762,  0.75975482,  1.13019796,  1.55216138])

In [76]:
sorted(arr, reverse=False)
arr

array([-1.22878754, -1.15386311, -1.05900859, -0.77331637, -0.25873269,
        0.07576187,  0.11760762,  0.75975482,  1.13019796,  1.55216138])

Ordenar en sentido inverso

In [73]:
sorted(arr, reverse = True)
arr

array([-1.22878754, -1.15386311, -1.05900859, -0.77331637, -0.25873269,
        0.07576187,  0.11760762,  0.75975482,  1.13019796,  1.55216138])

Y pedir elementos distintos:

In [77]:
arr = np.array([0, 0, 1, 1, 2, 2])
np.unique(arr)

array([0, 1, 2])